socket-server:
  port: 8085
  host: 127.0.0.1

server:
  port: 8082

socket:
  client:
    event:
      read-message: read-message

# Redis Configuration
spring:
  data:
    redis:
      host: localhost
      port: 6380
      password: eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81

# Messaging Service Configuration
services:
  messaging:
    base-url: 127.0.0.1